# Collector specific configuration
base_url: "http://api.gcfund.org/v1"

# Funded Activities
title_activities: "Global Climate Funded Activities"
resource_activities: "Climate funded activities"
description_activities: "A list of climate funded activities"

hxl_tags_activities:
  "Ref #": "#reference+id"
  "Modality": "#modality"
  "Project Name": "#project+title"
  "Entity": "#org+implementing"
  "Countries": "#country+name"
  "BM": "#board+meeting+id"
  "Sector": "#sector+name"
  "Theme": "#theme+name"
  "Project Size": "#project+size"
  "Approved Date": "#date+approved"
  "ESS Category": "#category+risk"
  "FA Financing": "#finance+funded+usd"
  "Website": "#url+website"

# Countries
title_countries: "Global Climate Funded Countries"
resource_countries: "Funded countries"
description_countries: "List of funded countries"

hxl_tags_countries:
  "ISO3": "#country+code"
  "Country Name": "#country+name"
  "Region": "#region+name"
  "SIDS": "#country+is_sids+flag"
  "LDCs": "#country+is_ldc+flag"
  "# RP": "#count+readiness_programmes"
  "# FA": "#count+funded_activities"
  "RP Financing": "#finance+readiness+usd"
  "FA Financing": "#finance+funded+usd"

# Entities
title_entities: "Global Climate Funding Entities"
resource_entities: "Entity funding"
description_entities: "Shows accreditation process stage of entities"

hxl_tags_entities:
  "Entity": "#org+implementing+acronym"
  "Name": "#org+implementing+name"
  "Country": "#country+name"
  "DAE": "#org+is_dae+flag"
  "Type": "#org+type"
  "Stage": "#org+stage"
  "BM": "#board+meeting+id"
  "Size": "#org+size"
  "Sector": "#sector+name"
  "# Approved": "#count+approved"
  "FA Financing": "#finance+funded+usd"

# Readiness
title_readiness: "Global Climate Funding Readiness"
resource_readiness: "Climate funding readiness"
description_readiness: "Climate funding status"

hxl_tags_readiness:
  "Ref #": "#reference+id"
  "Activity": "#activity"
  "Project Title": "#project+title"
  "Country": "#country+name"
  "Delivery Partner": "#delivery+partner"
  "Region": "#region"
  "Status": "#status"
  "Approved Date": "#date+approved"
  "Financing": "#financing+value+usd"

tags:
  - climate-weather
  - funding

caveats_activities: |
  1. Please note that the readiness grant information provided in the ODL includes the approved grants only.
  2. The number of approved grants in ODL Readiness covers only the Readiness proposals approved with the logical framework as per the Readiness Preparatory Support Strategies approved by the Board (i.e., excluding technical assistance grants, workshop activities, and structured dialogues executed with the Readiness budget).
  3. For multi-country projects, financial information per country is equally divided unless the allocation % is specified.
  4. The number of NAP support grants, DAE support grants, grants with CR submitted, and grants closed are included in the total number of approved grants as the subsets of the approved grants.

  ### Glossary

  **Activity**
  Four areas of Readiness support (Adaptation Planning, NDA Strengthening, Strategic Framework, Support for direct access entities)

  **Agreement Type**
  Three types of Readiness agreement

    1. Framework Agreement – An umbrella agreement laying out the terms and conditions for delivery partners and the GCF regarding the implementation of a portfolio of readiness support requests (grants)
    2. General Grant Agreement – A bilateral agreement between an NDA or delivery partner and the GCF stating the terms and conditions regarding the implementation of a single readiness support request or grant.
    3. Statement of work for PPF Service.

  **Region**
  GCF Region: Africa, Asia-Pacific, Eastern Europe, Latin America and the Caribbean

  **Country**
  Recipient country name

  **Delivery Partner**
  Institutions selected by an NDA or focal point to implement activities approved under the Readiness Programme.

  **SIDS**
  'Yes' returns only readiness grants targeting Small Island Developing States

  **LDCs**
  'Yes' returns only readiness grants targeting Least Developed Countries

  **NAP**
  The NAP process is a strategic process that enables countries to identify and address their medium- and long-term requirements

  **Status**
  Grant status types: Cancelled, Closed, Disbursed, In legal processing, Legal Agreement Effective

  **Approved Date From**
  Readiness grant approval date range selection start point

  **Approved Date To**
  Readiness grant approval date range selection end point

  **Regional**
  ‘Yes’ returns only regional readiness grants
caveats_countries: |
  For multi-country projects, financial information per country is equally divided unless the allocation % is specified.

  ### Glossary

  **Region**
  GCF Region: Africa, Asia-Pacific, Eastern Europe, Latin America and the Caribbean.

  **SIDS**
  'Yes' returns only countries classified as Small Island Developing States.

  **LDCs**
  'Yes' returns only countries classified as Least Developed Countries.
caveats_entities: |
  ### Glossary

  **DAE**
  'Yes' returns only entities classified as Direct Access Entities.

  **Type**
  Three entity types - International Access Entity (IAE) or National Access Entity or Regional Access Entity.

  **Stage**
  Select an entity accreditation process stage.

  **BM**
  Accreditation board meeting.

  **Size**
  Entity size.
caveats_readiness: |
  Please note that the readiness grant information provided in the ODL includes the approved grants only.
  The number of approved grants in ODL Readiness covers only the Readiness proposals approved with the logical framework as per the Readiness Preparatory Support Strategies approved by the Board (i.e., excluding technical assistance grants, workshop activities, and structured dialogues executed with the Readiness budget).
  For multi-country projects, financial information per country is equally divided unless the allocation % is specified.
  The number of NAP support grants, DAE support grants, grants with CR submitted, and grants closed are included in the total number of approved grants as the subsets of the approved grants.

  ### Glossary

  **Activity**
  Four areas of Readiness support (Adaptation Planning, NDA Strengthening, Strategic Framework, Support for direct access entities)

  **Agreement Type**
  Three types of Readiness agreement

    1. Framework Agreement – An umbrella agreement laying out the terms and conditions for delivery partners and the GCF regarding the implementation of a portfolio of readiness support requests (grants)
    2. General Grant Agreement – A bilateral agreement between an NDA or delivery partner and the GCF stating the terms and conditions regarding the implementation of a single readiness support request or grant.
    3. Statement of work for PPF Service.

  **Region**
  GCF Region: Africa, Asia-Pacific, Eastern Europe, Latin America and the Caribbean

  **Country**
  Recipient country name

  **Delivery Partner**
  Institutions selected by an NDA or focal point to implement activities approved under the Readiness Programme.

  **SIDS**
  'Yes' returns only readiness grants targeting Small Island Developing States

  **LDCs**
  'Yes' returns only readiness grants targeting Least Developed Countries

  **NAP**
  The NAP process is a strategic process that enables countries to identify and address their medium- and long-term requirements

  **Status**
  Grant status types: Cancelled, Closed, Disbursed, In legal processing, Legal Agreement Effective

  **Approved Date From**
  Readiness grant approval date range selection start point

  **Approved Date To**
  Readiness grant approval date range selection end point

  **Regional**
  ‘Yes’ returns only regional readiness grants
