# Collector specific configuration
base_url: "http://api.gcfund.org/v1"

# Funded Activities
title_activities: "GCF Funded Activities"
resource_activities: "Climate funded activities"
description_activities: "A list of climate funded activities"

notes_activities: "This dataset provides a list of climate funded activities showing the modality, project, name of entity, countries funded, the sector, theme, project size, ESS Category and FA financing."

caveats_activities: |
  1. Please note that the readiness grant information provided in the ODL includes the approved grants only.
  2. The number of approved grants in ODL Readiness covers only the Readiness proposals approved with the logical framework as per the Readiness Preparatory Support Strategies approved by the Board (i.e., excluding technical assistance grants, workshop activities, and structured dialogues executed with the Readiness budget).
  3. For multi-country projects, financial information per country is equally divided unless the allocation % is specified.
  4. The number of NAP support grants, DAE support grants, grants with CR submitted, and grants closed are included in the total number of approved grants as the subsets of the approved grants.

  [Link to Glossary](https://data.greenclimate.fund/public/data/projects)

# Countries
title_countries: "GCF Funded Countries"
resource_countries: "Funded countries"
description_countries: "List of funded countries"

notes_countries: "This dataset shows funding for countries classified as small Island developing States and countries classified as Least Developed Countries."

caveats_countries: |
  For multi-country projects, financial information per country is equally divided unless the allocation % is specified.

  [Link to Glossary](https://data.greenclimate.fund/public/data/countries)


# Entities
title_entities: "GCF Accredited Entities"
resource_entities: "Entity funding"
description_entities: "Shows accreditation process stage of entities"

notes_entities: "This dataset shows the climate funding entity accreditation process stage."

caveats_entities: |
  [Link to Glossary](https://data.greenclimate.fund/public/data/entities)

# Readiness
title_readiness: "GCF Readiness Programmes"
resource_readiness: "Climate funding readiness"
description_readiness: "Climate funding status"

notes_readiness: "This dataset shows the climate funding status."

caveats_readiness: |
  Please note that the readiness grant information provided in the ODL includes the approved grants only.
  The number of approved grants in ODL Readiness covers only the Readiness proposals approved with the logical framework as per the Readiness Preparatory Support Strategies approved by the Board (i.e., excluding technical assistance grants, workshop activities, and structured dialogues executed with the Readiness budget).
  For multi-country projects, financial information per country is equally divided unless the allocation % is specified.
  The number of NAP support grants, DAE support grants, grants with CR submitted, and grants closed are included in the total number of approved grants as the subsets of the approved grants.

  [Link to Glossary](https://data.greenclimate.fund/public/data/readiness)

tags:
  - climate-weather
  - funding
